### DISCUSSION TITLE
Help setting up SSO/OIDC with Authentik

### DISCUSSION THREAD

**Discussion by dhop90** [enchant97/note-mark#237] [Q&A]
Trying to configure SSO/OIDC using ghcr.io/enchant97/note-mark-aio:0.16.2 with Authentik as authentication provider is not working.

Upon trying to login via Authentik, it errors with "Error exchanging details with provider."

Note-mark configuration
```
        - env:
            - name: CORS_ORIGINS
              value: https://notemark.example.org
            - name: DB__TYPE
              value: postgres
            - name: DB__URI
              value: >-
                host=qnap.example.org user=notemark
                password=<password> dbname=notemark port=5432
                sslmode=disable TimeZone=America/Chicago
            - name: JWT_SECRET
              value: <secret>
            - name: OIDC__DISPLAY_NAME
              value: Authentik
            - name: OIDC__PROVIDER_NAME
              value: authentik
            - name: OIDC__ISSUER_URL
              value: https://auth.example.org/application/o/notemark/
            - name: OIDC__CLIENT_ID
              value: <client ID>
            - name: OIDC__ENABLE_USER_CREATION
              value: 'false'
            - name: ENABLE_INTERNAL_SIGNUP
              value: 'false'
            - name: ENABLE_INTERNAL_LOGIN
              value: 'true'
            - name: OIDC__EMAIL_FIELD
              value: email
            - name: OIDC__NAME_FIELD
              value: name
            - name: OIDC__SCOPES
              value: openid profile email notemark-claims
```
Authentik config:
```
Name
notemark
Assigned to application
[notemark](https://auth.example.org/if/admin/#/core/applications/notemark)
Client type
Public
Client ID
<client ID>
Redirect URIs
strict: https://notemark.example.org/oidc-callback
```
```
OpenID Configuration URL 
https://auth.example.org/application/o/notemark/.well-known/openid-configuration
OpenID Configuration Issuer 
https://auth.example.org/application/o/notemark/
```

For the life of me, I can't get this working.
