### ISSUE TITLE
(BUG) GFM Double Brace not escaping.

### ISSUE THREAD

**Issue by PaulMColeman** [enchant97/note-mark#231]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is This A Security Issue?

- [x] This is not a security issue

### Describe The Problem

When trying to escape a double brace {{ it does not correctly escape it.

```
- hosts: all
  tasks:
    - name: Renders but shows backslashes in render.
        key: "{\{ lookup('file', 'files/file.txt') }\}"
```

```
- hosts: all
  tasks:
    - name: Will not Render:
        key: "{{ lookup('file', 'files/file.txt') }}"
```

```
- hosts: all
  tasks:
    - name: Will not render even wrapping expression in Single quotes:
        key: '{{ lookup("file", "files/file.txt") }}'
```

### Expected Behavior

Should render the text correctly like in this comment:
```
- hosts: all
  tasks:
    - name: Should Render this:
        key: "{{ lookup('file', 'files/file.txt') }}"
```

### Steps To Reproduce

1. Create New Note
2. paste text into note
```
- hosts: all
  tasks:
    - name: Should render:
        key: "{{ lookup('file', 'files/file.txt') }}"
```
3. Save & Preview, will result in `Unable to render markdown, maybe you got the templating syntax incorrect?`

### Environment

Docker Container ghcr.io/enchant97/note-mark-aio
```
docker image inspect ghcr.io/enchant97/note-mark-aio
[
    {
        "Id": "sha256:04405e28349c6bb6be83956dd819f6286bd2164f88d08a7b592a9a0561d26dea",
        "RepoTags": [
            "ghcr.io/enchant97/note-mark-aio:latest"
        ],
        "RepoDigests": [
            "ghcr.io/enchant97/note-mark-aio@sha256:9a1de3608718a40341d76aa95a5a0494180c157ddc9131fb1ab65b93fc50dab2"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2025-03-28T14:32:07.418072905Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
                "BIND__HOST=0.0.0.0",
                "BIND__PORT=8000",
                "DB__URI=/data/db.sqlite",
                "DB__TYPE=sqlite",
                "DATA_PATH=/data",
                "STATIC_PATH=/static"
            ],
            "Cmd": [
                "serve"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "./note-mark"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.created": "2025-03-28T14:31:57.453Z",
                "org.opencontainers.image.description": "Note Mark is a lighting fast and minimal; web-based Markdown notes app.",
                "org.opencontainers.image.licenses": "AGPL-3.0",
                "org.opencontainers.image.revision": "01de237ba0eee90b31c884e9a84d36af12e693b6",
                "org.opencontainers.image.source": "https://github.com/enchant97/note-mark",
                "org.opencontainers.image.title": "note-mark",
                "org.opencontainers.image.url": "https://github.com/enchant97/note-mark",
                "org.opencontainers.image.version": "0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 33178857,
        "VirtualSize": 33178857,
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:b7f712dabf336ac1018bcd8173a3fffbe1e7529ae81dd6bee803e32fed0a50b6",
                "sha256:8fa10c0194df9b7c054c90dbe482585f768a54428fc90a5b78a0066a123b1bba",
                "sha256:9e81792d7b005cda0d93befa0d41aa1381f40141bdf954dfb388188efa6e8226",
                "sha256:4d049f83d9cf21d1f5cc0e11deaf36df02790d0e60c1a3829538fb4b61685368",
                "sha256:af5aa97ebe6ce1604747ec1e21af7136ded391bcabe4acef882e718a87c86bcc",
                "sha256:6f1cdceb6a3146f0ccb986521156bef8a422cdbb0863396f7f751f575ba308f4",
                "sha256:bbb6cacb8c82e4da4e8143e03351e939eab5e21ce0ef333c42e637af86c5217b",
                "sha256:2a92d6ac9e4fcc274d5168b217ca4458a9fec6f094ead68d99c77073f08caac1",
                "sha256:1a73b54f556b477f0a8b939d13c504a3b4f4db71f7a09c63afbc10acb3de5849",
                "sha256:f4aee9e53c42a22ed82451218c3ea03d1eea8d6ca8fbe8eb4e950304ba8a8bb3",
                "sha256:b336e209998fa5cf0eec3dabf93a21194198a35f4f75612d8da03693f8c30217",
                "sha256:4c1ac38357dbd0be27af41488cb0644fe675df007412991c122bb195ecc58b84",
                "sha256:51c041dc6508d315a3edeb654dfc67d65644635a93b405fcd31550553b2f995b"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
