### ISSUE TITLE
(BUG) OIDC does not work with Authelia

### ISSUE THREAD

**Issue by Stylee32** [enchant97/note-mark#235]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is This A Security Issue?

- [x] This is not a security issue

### Describe The Problem

When trying to log into Note Mark using Authelia for OIDC, it errors on Note Mark with the following:
Error exchanging details with provider.

The URL changes to the following:
https://wiki.example.com/oidc-callback?error=invalid_state&error_description=The+state+is+missing+or+does+not+have+enough+characters+and+is+therefore+considered+too+weak.+Request+parameter+%27state%27+must+be+at+least+be+8+characters+long+to+ensure+sufficient+entropy.&iss=https%3A%2F%2Fauth.example.com

Authelia reports in the logs:
time="2025-06-01T23:09:30+01:00" level=error msg="Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy." method=GET path=/api/oidc/authorization remote_ip=x.x.x.x

### Expected Behavior

Logging in via Authelia should work as expected

### Steps To Reproduce

1. Setup Authelia with the following config
```
      - client_id: 'notemark'
        client_name: 'notemark'
        public: true
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
         - 'https://wiki.example.com/oidc-callback'
        scopes:
         - 'openid'
         - 'profile'
```
2. Setup note-mark with the following config:

> OIDC__CLIENT_ID=notemark
> OIDC__ISSUER_URL=https://auth.example.com
> OIDC__DISPLAY_NAME=AUTHELIA
> OIDC__PROVIDER_NAME=AUTHELIA

### Environment

Docker on Ubuntu 22.04, using Caddy as a reverse proxy 

### Extra Context

I believe you're using this package - https://www.npmjs.com/package/openid-client- it states 

> 
>   /**
>    * We cannot be sure the server supports PKCE so we're going to use state too.
>    * Use of PKCE is backwards compatible even if the AS doesn't support it which
>    * is why we're using it regardless. Like PKCE, random state must be generated
>    * for every redirect to the authorization_endpoint.
>    */

It seems as if note-mark is not appending the state when building the URL, so is causing Authelia to error
I can see in the access logs:
/api/oidc/authorization?redirect_uri=https%3A%2F%2Fwiki.example.com%2Foidc-callback&scope=openid+profile&code_challenge=(code_here)&code_challenge_method=S256&client_id=notemark&response_type=code
