### ISSUE TITLE
(BUG) Failed authentication with Authelia

### ISSUE THREAD

**Issue by Zepmann** [enchant97/note-mark#240]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is This A Security Issue?

- [x] This is not a security issue

### Describe The Problem

When configured for authentication through OIDC with Authelia as the OIDC provider, Note Mark fails when the "Login with Authelia" button is used on the login screen. The error as reported by the browser:

```
Internal Server Error 500, unexpected error occurred, oidc: failed to unmarshal claims: invalid character 'A' looking for beginning of value
```

The character 'A' in this example is a different character with every attempt.

### Expected Behavior

Login should be successful.

### Environment

Tested with the latest stable versions of Note Mark and Authelia. Both Note Mark and Authelia run in Docker. Authelia is successfully authenticating other OpenID clients.

Note Mark configuration:
```
  environment:
      - JWT_SECRET=(removed)
      - CORS_ORIGINS=https://notes.example.com
      - DB__TYPE=postgres
      - DB__URI=host=postgres user=notemark password=(removed) dbname=notemark port=5432 sslmode=disable TimeZone=(removed)>
      - ENABLE_INTERNAL_SIGNUP=false
      - ENABLE_INTERNAL_LOGIN=false
      - OIDC__DISPLAY_NAME=Authelia
      - OIDC__PROVIDER_NAME=authelia
      - OIDC__ISSUER_URL=https://auth.example.com
      - OIDC__CLIENT_ID=notemark
      - OIDC__ENABLE_USER_CREATION=true
```

Authelia configuration:
```
identity_providers:
  oidc:
    clients:
    -
      client_name: 'Notemark'
      client_id: 'notemark'
      public: true
      authorization_policy: 'two_factor'
      require_pkce: true
      pkce_challenge_method: 'S256'
      redirect_uris:
        - 'https://notes.example.com/oidc-callback'
      scopes:
        - 'openid'
        - 'profile'
```

### Extra Context

I found issue #235. Although that issue should be solved, I have not found any confirmation that Note Mark works with Authelia. Documentation is limited. A minimal working example for configuring Authelia would be very welcome, if this turns out to be a configuration issue. 😉
