### ISSUE TITLE
Create account never gets enabled

### ISSUE THREAD

**Issue by dartie** [enchant97/note-mark#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

After deployed the application using docker-compose, I connect to 127.0.0.1:8000 and fill in the form for creating an account, but the button **CREATE USER** never gets enabled and I can't create the account.

### Expected Behavior

The account is created and I can login using the credentials

### Steps To Reproduce

1. Create file `docker-compose.yml`

```yml
version: "3"

volumes:
  data:

services:
  backend:
    image: ghcr.io/enchant97/note-mark-backend:0.6.0

    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      # !!! REPLACE These !!!
      JWT_SECRET: "bXktc2VjcmV0"
      CORS_ORIGINS: "*"
    ports:
      - 8001:8000

  frontend:
    image: ghcr.io/enchant97/note-mark-frontend:0.6.0

    restart: unless-stopped
    ports:
      - 8000:8000
```

2. Run `sudo docker-compose up -d`
3. From the broswer connect to http://127.0.0.1:8000
4. Click **Need an account**
5. Fill the fields using a secure password like `P@ssword123` -> the button **Create user** is greyed out

### Environment

Fedora 38 KDE
